language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.0"
#  - rbx-2.2.1   # Check https://travis-ci.org/rubinius/travis-canary before enabling
  - jruby-19mode
  - jruby-head
allow_failures:
  rvm:
    - ruby-head
